### ISSUE TITLE
fatal error C1083: Cannot open source file: '..\src\bufferutil.c'

### ISSUE THREAD

**Issue by drcmda** [electron/electron-packager#1232]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
Electron Packager 15.2.0
Node v12.18.2
Host Operating system: darwin 20.3.0 (x64)
* **Electron Version:**
v12.0.1
* **Operating System:**
Windows 10 (1803)

### Expected Behavior
no crashes

### Actual Behavior
```
⠏ Preparing native dependencies: 0 / 1Warning: Missing input files:
C:\Users\RAINER~1\AppData\Local\Temp\electron-packager\win32-x64\electron-test-win32-x64\resources\app\node_modules\bufferutil\build\..\src\bufferutil.c
⠋ Preparing native dependencies: 0 / 1gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   map: [Function]
gyp info spawn args ]
⠸ Preparing native dependencies: 0 / 1Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
⠼ Preparing native dependencies: 0 / 1  bufferutil.c
⠴ Preparing native dependencies: 0 / 1c1 : fatal error C1083: Cannot open source file: '..\src\bufferutil.c': No such file or directory [C:\Users\RainerWeigel\AppData\Local\Temp\electron-packager\win32-x64\electron
-test-win32-x64\resources\app\node_modules\bufferutil\build\bufferutil.vcxproj]
:heavy_multiplication_x: Preparing native dependencies: 0 / 1
An unhandled error has occurred inside Forge:
node-gyp failed to rebuild 'C:\Users\RAINER~1\AppData\Local\Temp\electron-packager\win32-x64\electron-test-win32-x64\resources\app\node_modules\bufferutil'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
Error: node-gyp failed to rebuild 'C:\Users\RAINER~1\AppData\Local\Temp\electron-packager\win32-x64\electron-test-win32-x64\resources\app\node_modules\bufferutil'.
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
    at ModuleRebuilder.rebuildNodeGypModule (D:\ClassCAD\electron-starter\node_modules\electron-rebuild\src\module-rebuilder.ts:231:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### To Reproduce
This is a generic current-gen electron-forge project.

    yarn create electron-app my-new-app

### Additional Information

```json
{
  "name": "electron-test",
  "productName": "electron-test",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": "electron/main.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "echo \"No linting configured\""
  },
  "keywords": [],
  "author": {
    "name": "Paul Henschel",
    "email": "drcmda@gmail.com"
  },
  "license": "MIT",
  "config": {
    "forge": {
      "packagerConfig": {
        "prune": true,
        "ignore": [
          "src",
          ".yarnrc",
          ".npmrc",
          ".gitignore"
        ]
      },
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "electron_test"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  },
  "dependencies": {
    "@awvinf/classcad_buerlidemo": "^1.1.4",
    "awv3-node": "^10.0.3",
    "electron-squirrel-startup": "^1.0.0"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.54",
    "@electron-forge/maker-deb": "^6.0.0-beta.54",
    "@electron-forge/maker-rpm": "^6.0.0-beta.54",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.54",
    "@electron-forge/maker-zip": "^6.0.0-beta.54",
    "@electron-forge/plugin-webpack": "^6.0.0-beta.54",
    "electron": "12.0.1"
  }
```

**Comment by malept** [comment]
This is because you're ignoring any file/folder containing `src` in its path, including `node_modules\bufferutil\src\bufferutil.c`. You should be more specific about your ignored regular expressions, for example `^/src`.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).

**Comment by drcmda** [comment]
Interesting, thanks, I believe that's forges default config.

**Comment by malept** [comment]
> Interesting, thanks, I believe that's forges default config.

It's not, you have this in your `packagerConfig`: 
```json
"ignore": [
          "src",
          ".yarnrc",
          ".npmrc",
          ".gitignore"
        ]
```
