### ISSUE TITLE
ci: dest already exists flake

### ISSUE THREAD

**Issue by erickzhao** [electron/electron-packager#1421]
```
#!/bin/bash -eo pipefail test/ci/_before_script.js
Downloading Electron v1.4.13 before running tests...
Error: dest already exists.
     at /home/circleci/project/node_modules/@electron/get/node_modules/fs-extra/lib/move/move.js:41:31
     at /home/circleci/project/node_modules/@electron/get/node_modules/universalify/index.js:23:46
  Exited with code exit status 1 CircleCI received exit code 1
```

https://app.circleci.com/pipelines/github/electron/electron-packager/659/workflows/2f15c4a1-abc2-49a9-ac13-81ad1561b738/jobs/2958

**Comment by erickzhao** [comment]
Additional debug info:

```
Downloading Electron v1.4.13 before running tests...
  @electron/get:index Checking the cache (undefined) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +0ms
  @electron/get:index Cache miss +3ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt to /tmp/electron-download-PI1wXV/SHASUMS256.txt with options: undefined +59ms
  @electron/get:cache Moving /tmp/electron-download-PI1wXV/SHASUMS256.txt to /home/circleci/.cache/electron/4660c2617dcac48c05988e181e4f7ff85132cd278bba79561816d3e7da1cc50c/SHASUMS256.txt +0ms
  @electron/get:index No arch found, defaulting to the host arch +162ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-linux-ia32.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-ia32.zip) +1ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-win32-ia32.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-win32-ia32.zip) +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-darwin-x64.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-darwin-x64.zip) +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-linux-x64.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-x64.zip) +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-mas-x64.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-mas-x64.zip) +1ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-win32-x64.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-win32-x64.zip) +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v1.4.13-linux-armv7l.zip (https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-armv7l.zip) +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for electron-v6.0.0-darwin-x64.zip (https://github.com/electron/electron/releases/download/v6.0.0/electron-v6.0.0-darwin-x64.zip) +0ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-ia32.zip to /tmp/electron-download-3O1eel/electron-v1.4.13-linux-ia32.zip with options: undefined +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-win32-ia32.zip to /tmp/electron-download-1OI9ji/electron-v1.4.13-win32-ia32.zip with options: undefined +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-darwin-x64.zip to /tmp/electron-download-Ws7TgH/electron-v1.4.13-darwin-x64.zip with options: undefined +1ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-x64.zip to /tmp/electron-download-hS3Oc8/electron-v1.4.13-linux-x64.zip with options: undefined +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-mas-x64.zip to /tmp/electron-download-Vc5xwC/electron-v1.4.13-mas-x64.zip with options: undefined +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-win32-x64.zip to /tmp/electron-download-mJHTDK/electron-v1.4.13-win32-x64.zip with options: undefined +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-armv7l.zip to /tmp/electron-download-lbtzTp/electron-v1.4.13-linux-armv7l.zip with options: undefined +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v6.0.0/electron-v6.0.0-darwin-x64.zip to /tmp/electron-download-T8gn8V/electron-v6.0.0-darwin-x64.zip with options: undefined +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +2s
  @electron/get:index Cache miss +1ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt to /tmp/electron-download-Zcln1Z/SHASUMS256.txt with options: undefined +1ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +26ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt to /tmp/electron-download-oB433U/SHASUMS256.txt with options: undefined +0ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +31ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt to /tmp/electron-download-gaC39r/SHASUMS256.txt with options: undefined +1ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +26ms
  @electron/get:index Cache miss +0ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt to /tmp/electron-download-mSMl8f/SHASUMS256.txt with options: undefined +1ms
  @electron/get:index Checking the cache (/home/circleci/.electron) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +28ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt to /tmp/electron-download-SeHepQ/SHASUMS256.txt with options: undefined +1ms
  @electron/get:cache Moving /tmp/electron-download-Zcln1Z/SHASUMS256.txt to /home/circleci/.electron/4660c2617dcac48c05988e181e4f7ff85132cd278bba79561816d3e7da1cc50c/SHASUMS256.txt +2s
  @electron/get:index Checking the cache (/home/circleci/.electron) for SHASUMS256.txt (https://github.com/electron/electron/releases/download/v1.4.13/SHASUMS256.txt) +26ms
  @electron/get:index Cache hit +2ms
  @electron/get:cache Moving /tmp/electron-download-gaC39r/SHASUMS256.txt to /home/circleci/.electron/4660c2617dcac48c05988e181e4f7ff85132cd278bba79561816d3e7da1cc50c/SHASUMS256.txt +12ms
  @electron/get:cache * Replacing existing file +0ms
  @electron/get:cache Moving /tmp/electron-download-mSMl8f/SHASUMS256.txt to /home/circleci/.electron/4660c2617dcac48c05988e181e4f7ff85132cd278bba79561816d3e7da1cc50c/SHASUMS256.txt +7ms
  @electron/get:cache Moving /tmp/electron-download-oB433U/SHASUMS256.txt to /home/circleci/.electron/4660c2617dcac48c05988e181e4f7ff85132cd278bba79561816d3e7da1cc50c/SHASUMS256.txt +12ms
  @electron/get:cache * Replacing existing file +1ms
  @electron/get:cache Moving /tmp/electron-download-SeHepQ/SHASUMS256.txt to /home/circleci/.electron/4660c2617dcac48c05988e181e4f7ff85132cd278bba79561816d3e7da1cc50c/SHASUMS256.txt +18ms
Error: dest already exists.
    at /home/circleci/project/node_modules/@electron/get/node_modules/fs-extra/lib/move/move.js:41:31
    at /home/circleci/project/node_modules/@electron/get/node_modules/universalify/index.js:23:46
```
